/**
 * Manufacturer by id
 * 
 * @link https://www.midi.org/specifications-old/item/manufacturer-id-numbers
 * @created 2024-01-18
 */

export default {
  0x00: {
    0x00: {
      0x01: 'Time/Warner Interactive',
      0x02: 'Advanced Gravis Comp. Tech Ltd.',
      0x03: 'Media Vision',
      0x04: 'Dornes Research Group',
      0x05: 'K-Muse',
      0x06: 'Stypher',
      0x07: 'Digital Music Corp.',
      0x08: 'IOTA Systems',
      0x09: 'New England Digital',
      0x0a: 'Artisyn',
      0x0b: 'IVL Technologies Ltd.',
      0x0c: 'Southern Music Systems',
      0x0d: 'Lake Butler Sound Company',
      0x0e: 'Alesis Studio Electronics',
      0x0f: 'Sound Creation',
      //0x01: 'Time/Warner Interactive',// duplicate form www
      0x10: 'DOD Electronics Corp.',
      0x11: 'Studer-Editech',
      0x12: 'Sonus',
      0x13: 'Temporal Acuity Products',
      0x14: 'Perfect Fretworks',
      0x15: 'KAT Inc.',
      0x16: 'Opcode Systems',
      0x17: 'Rane Corporation',
      0x18: 'Anadi Electronique',
      0x19: 'KMX',
      0x1a: 'Allen & Heath Brenell',
      0x1b: 'Peavey Electronics',
      0x1c: '360 Systems',
      0x1d: 'Spectrum Design and Development',
      0x1e: 'Marquis Music',
      0x1f: 'Zeta Systems',
      0x20: 'Axxes (Brian Parsonett)',
      0x21: 'Orban',
      0x22: 'Indian Valley Mfg.',
      0x23: 'Triton',
      0x24: 'KTI',
      0x25: 'Breakaway Technologies',
      0x26: 'Leprecon / CAE Inc.',
      0x27: 'Harrison Systems Inc.',
      0x28: 'Future Lab/Mark Kuo',
      0x29: 'Rocktron Corporation',
      0x2a: 'PianoDisc',
      0x2b: 'Cannon Research Group',
      0x2c: 'Reserved',
      0x2d: 'Rodgers Instrument LLC',
      0x2e: 'Blue Sky Logic',
      0x2f: 'Encore Electronics',
      0x30: 'Uptown',
      0x31: 'Voce',
      0x32: 'CTI Audio, Inc. (Musically Intel. Devs.)',
      0x33: 'S3 Incorporated',
      0x34: 'Broderbund / Red Orb',
      0x35: 'Allen Organ Co.',
      0x36: 'Reserved',
      0x37: 'Music Quest',
      0x38: 'Aphex',
      0x39: 'Gallien Krueger',
      0x3a: 'IBM',
      0x3b: 'Mark Of The Unicorn',
      0x3c: 'Hotz Corporation',
      0x3d: 'ETA Lighting',
      0x3e: 'NSI Corporation',
      0x3f: 'Ad Lib, Inc.',
      0x40: 'Richmond Sound Design',
      0x41: 'Microsoft',
      0x42: 'Mindscape (Software Toolworks)',
      0x43: 'Russ Jones Marketing / Niche',
      0x44: 'Intone',
      0x45: 'Advanced Remote Technologies',
      0x46: 'White Instruments',
      0x47: 'GT Electronics/Groove Tubes',
      0x48: 'Pacific Research & Engineering',
      0x49: 'Timeline Vista, Inc.',
      0x4a: 'Mesa Boogie Ltd.',
      0x4b: 'FSLI',
      0x4c: 'Sequoia Development Group',
      0x4d: 'Studio Electronics',
      0x4e: 'Euphonix, Inc',
      0x4f: 'InterMIDI, Inc.',
      0x50: 'MIDI Solutions Inc.',
      0x51: '3DO Company',
      0x52: 'Lightwave Research / High End Systems',
      0x53: 'Micro-W Corporation',
      0x54: 'Spectral Synthesis, Inc.',
      0x55: 'Lone Wolf',
      0x56: 'Studio Technologies Inc.',
      0x57: 'Peterson Electro-Musical Product, Inc.',
      0x58: 'Atari Corporation',
      0x59: 'Marion Systems Corporation',
      0x5a: 'Design Event',
      0x5b: 'Winjammer Software Ltd.',
      0x5c: 'AT&T Bell Laboratories',
      0x5d: 'Reserved',
      0x5e: 'Symetrix',
      0x5f: 'MIDI the World',
      0x60: 'Spatializer',
      0x61: "Micros 'N MIDI",
      0x62: 'Accordians International',
      0x63: 'EuPhonics (now 3Com)',
      0x64: 'Musonix',
      0x65: 'Turtle Beach Systems (Voyetra)',
      0x66: 'Loud Technologies / Mackie',
      0x67: 'Compuserve',
      0x68: 'BEC Technologies',
      0x69: 'QRS Music Inc',
      0x6a: 'P.G. Music',
      0x6b: 'Sierra Semiconductor',
      0x6c: 'EpiGraf',
      0x6d: 'Electronics Diversified Inc',
      0x6e: 'Tune 1000',
      0x6f: 'Advanced Micro Devices',
      0x70: 'Mediamation',
      0x71: 'Sabine Musical Mfg. Co. Inc.',
      0x72: 'Woog Labs',
      0x73: 'Micropolis Corp',
      0x74: 'Ta Horng Musical Instrument',
      0x75: 'e-Tek Labs (Forte Tech)',
      0x76: 'Electro-Voice',
      0x77: 'Midisoft Corporation',
      0x78: 'QSound Labs',
      0x79: 'Westrex',
      0x7a: 'Nvidia',
      0x7b: 'ESS Technology',
      0x7c: 'Media Trix Peripherals',
      0x7d: 'Brooktree Corp',
      0x7e: 'Otari Corp',
      0x7f: 'Key Electronics, Inc.'
    },
    0x01: {
      0x00: 'Shure Incorporated',
      0x01: 'AuraSound',
      0x02: 'Crystal Semiconductor',
      0x03: 'Conexant (Rockwell)',
      0x04: 'Silicon Graphics',
      0x05: 'M-Audio (Midiman)',
      0x06: 'PreSonus',
      0x08: 'Topaz Enterprises',
      0x09: 'Cast Lighting',
      0x0a: 'Microsoft Consumer Division',
      0x0b: 'Sonic Foundry',
      0x0c: 'Line 6 (Fast Forward) (Yamaha)',
      0x0d: 'Beatnik Inc',
      0x0e: 'Van Koevering Company',
      0x0f: 'Altech Systems',
      0x10: 'S & S Research',
      0x11: 'VLSI Technology',
      0x12: 'Chromatic Research',
      0x13: 'Sapphire',
      0x14: 'IDRC',
      0x15: 'Justonic Tuning',
      0x16: 'TorComp Research Inc.',
      0x17: 'Newtek Inc.',
      0x18: 'Sound Sculpture',
      0x19: 'Walker Technical',
      0x1a: 'Digital Harmony (PAVO)',
      0x1b: 'InVision Interactive',
      0x1c: 'T-Square Design',
      0x1d: 'Nemesys Music Technology',
      0x1e: 'DBX Professional (Harman Intl)',
      0x1f: 'Syndyne Corporation',
      0x20: 'Bitheadz',
      0x21: 'BandLab Technologies',
      0x22: 'Analog Devices',
      0x23: 'National Semiconductor',
      0x24: 'Boom Theory / Adinolfi Alternative Percussion',
      0x25: 'Virtual DSP Corporation',
      0x26: 'Antares Systems',
      0x27: 'Angel Software',
      0x28: 'St Louis Music',
      0x29: 'Passport Music Software LLC (Gvox)',
      0x2a: 'Ashley Audio Inc.',
      0x2b: 'Vari-Lite Inc.',
      0x2c: 'Summit Audio Inc.',
      0x2d: 'Aureal Semiconductor Inc.',
      0x2e: 'SeaSound LLC',
      0x2f: 'U.S. Robotics',
      0x30: 'Aurisis Research',
      0x31: 'Nearfield Research',
      0x32: 'FM7 Inc',
      0x33: 'Swivel Systems',
      0x34: 'Hyperactive Audio Systems',
      0x35: 'MidiLite (Castle Studios Productions)',
      0x36: 'Radikal Technologies',
      0x37: 'Roger Linn Design',
      0x38: 'TC-Helicon Vocal Technologies',
      0x39: 'Event Electronics',
      0x3a: 'Sonic Network Inc',
      0x3b: 'Realtime Music Solutions',
      0x3c: 'Apogee Digital',
      0x3d: 'Classical Organs, Inc.',
      0x3e: 'Microtools Inc.',
      0x3f: 'Numark Industries',
      0x40: 'Frontier Design Group, LLC',
      0x41: 'Recordare LLC',
      0x42: 'Starr Labs',
      0x43: 'Voyager Sound Inc.',
      0x44: 'Manifold Labs',
      0x45: 'Aviom Inc.',
      0x46: 'Mixmeister Technology',
      0x47: 'Notation Software',
      0x48: 'Mercurial Communications',
      0x49: 'Wave Arts',
      0x4a: 'Logic Sequencing Devices',
      0x4b: 'Axess Electronics',
      0x4c: 'Muse Research',
      0x4d: 'Open Labs',
      0x4e: 'Guillemot Corp',
      0x4f: 'Samson Technologies',
      0x50: 'Electronic Theatre Controls',
      0x51: 'Blackberry (RIM)',
      0x52: 'Mobileer',
      0x53: 'Synthogy',
      0x54: 'Lynx Studio Technology Inc.',
      0x55: 'Damage Control Engineering LLC',
      0x56: 'Yost Engineering, Inc.',
      0x57: 'Brooks & Forsman Designs LLC / DrumLite',
      0x58: 'Infinite Response',
      0x59: 'Garritan Corp',
      0x5a: 'Plogue Art et Technologie, Inc',
      0x5b: 'RJM Music Technology',
      0x5c: 'Custom Solutions Software',
      0x5d: 'Sonarcana LLC / Highly Liquid',
      0x5e: 'Centrance',
      0x5f: 'Kesumo LLC',
      0x60: 'Stanton (Gibson Brands)',
      0x61: 'Livid Instruments',
      0x62: 'First Act / 745 Media',
      0x63: 'Pygraphics, Inc.',
      0x64: 'Panadigm Innovations Ltd',
      0x65: 'Avedis Zildjian Co',
      0x66: 'Auvital Music Corp',
      0x67: 'You Rock Guitar (was: Inspired Instruments)',
      0x68: 'Chris Grigg Designs',
      0x69: 'Slate Digital LLC',
      0x6a: 'Mixware',
      0x6b: 'Social Entropy',
      0x6c: 'Source Audio LLC',
      0x6d: 'Ernie Ball / Music Man',
      0x6e: 'Fishman',
      0x6f: 'Custom Audio Electronics',
      0x70: 'American Audio/DJ',
      0x71: 'Mega Control Systems',
      0x72: 'Kilpatrick Audio',
      0x73: 'iConnectivity',
      0x74: 'Fractal Audio',
      0x75: 'NetLogic Microsystems',
      0x76: 'Music Computing',
      0x77: 'Nektar Technology Inc',
      0x78: 'Zenph Sound Innovations',
      0x79: 'DJTechTools.com',
      0x7a: 'Rezonance Labs',
      0x7b: 'Decibel Eleven',
      0x7c: 'CNMAT',
      0x7d: 'Media Overkill',
      0x7e: 'Confusion Studios',
      0x7f: 'moForte Inc'
    },
    0x02: {
      0x00: 'Miselu Inc',
      0x01: "Amelia's Compass LLC",
      0x02: 'Zivix LLC',
      0x03: 'Artiphon',
      0x04: 'Synclavier Digital',
      0x05: 'Light & Sound Control Devices LLC',
      0x06: 'Retronyms Inc',
      0x07: 'JS Technologies',
      0x08: 'Quicco Sound',
      0x09: 'A-Designs Audio',
      0x0a: 'McCarthy Music Corp',
      0x0b: 'Denon DJ',
      0x0c: 'Keith Robert Murray',
      0x0d: 'Google',
      0x0e: 'ISP Technologies',
      0x0f: 'Abstrakt Instruments LLC',
      0x10: 'Meris LLC',
      0x11: 'Sensorpoint LLC',
      0x12: 'Hi-Z Labs',
      0x13: 'Imitone',
      0x14: 'Intellijel Designs Inc.',
      0x15: 'Dasz Instruments Inc.',
      0x16: 'Remidi',
      0x17: 'Disaster Area Designs LLC',
      0x18: 'Universal Audio',
      0x19: 'Carter Duncan Corp',
      0x1a: 'Essential Technology',
      0x1b: 'Cantux Research LLC',
      0x1c: 'Hummel Technologies',
      0x1d: 'Sensel Inc',
      0x1e: 'DBML Group',
      0x1f: 'Madrona Labs',
      0x20: 'Mesa Boogie',
      0x21: 'Effigy Labs',
      0x22: 'Amenote',
      0x23: 'Red Panda LLC',
      0x24: 'OnSong LLC',
      0x25: 'Jamboxx Inc.',
      0x26: 'Electro-Harmonix ',
      0x27: 'RnD64 Inc',
      0x28: 'Neunaber Technology LLC ',
      0x29: 'Kaom Inc.',
      0x2a: 'Hallowell EMC',
      0x2b: 'Sound Devices, LLC',
      0x2c: 'Spectrasonics, Inc',
      0x2d: 'Second Sound, LLC',
      0x2e: '8eo (Horn)',
      0x2f: 'VIDVOX LLC',
      0x30: 'Matthews Effects',
      0x31: 'Bright Blue Beetle',
      0x32: 'Audio Impressions',
      0x33: 'Looperlative',
      0x34: 'Steinway',
      0x35: 'Ingenious Arts and Technologies LLC',
      0x36: 'DCA Audio',
      0x37: 'Buchla USA',
      0x38: 'Sinicon',
      0x39: 'Isla Instruments',
      0x3a: 'Soundiron LLC',
      0x3b: 'Sonoclast, LLC',
      0x3c: 'Copper and Cedar',
      0x3d: 'Whirled Notes',
      0x3e: 'Cejetvole, LLC',
      0x3f: 'DAWn Audio LLC',
      0x40: 'Space Brain Circuits',
      0x41: 'Caedence',
      0x42: 'HCN Designs, LLC (The MIDI Maker)',
      0x43: 'PTZOptics',
      0x44: 'Noise Engineering',
      0x45: 'Synthesia LLC',
      0x46: 'Jeff Whitehead Lutherie LLC',
      0x47: 'Wampler Pedals Inc.',
      0x48: 'Tapis Magique',
      0x49: 'Leaf Secrets',
      0x4a: 'Groove Synthesis'
    },
    0x20: {
      0x00: 'Dream SAS',
      0x01: 'Strand Lighting',
      0x02: 'Amek Div of Harman Industries',
      0x03: 'Casa Di Risparmio Di Loreto',
      0x04: 'Böhm electronic GmbH',
      0x05: 'Syntec Digital Audio',
      0x06: 'Trident Audio Developments',
      0x07: 'Real World Studio',
      0x08: 'Evolution Synthesis, Ltd',
      0x09: 'Yes Technology',
      0x0a: 'Audiomatica',
      0x0b: 'Bontempi SpA (Sigma)',
      0x0c: 'F.B.T. Elettronica SpA',
      0x0d: 'MidiTemp GmbH',
      0x0e: 'LA Audio (Larking Audio)',
      0x0f: 'Zero 88 Lighting Limited',
      0x10: 'Micon Audio Electronics GmbH',
      0x11: 'Forefront Technology',
      0x12: 'Studio Audio and Video Ltd.',
      0x13: 'Kenton Electronics',
      0x14: 'Celco/ Electrosonic',
      0x15: 'ADB',
      0x16: 'Marshall Products Limited',
      0x17: 'DDA',
      0x18: 'BSS Audio Ltd.',
      0x19: 'MA Lighting Technology',
      0x1a: 'Fatar SRL c/o Music Industries',
      0x1b: 'QSC Audio Products Inc.',
      0x1c: 'Artisan Clasic Organ Inc.',
      0x1d: 'Orla Spa',
      0x1e: 'Pinnacle Audio (Klark Teknik PLC)',
      0x1f: 'TC Electronics',
      0x20: 'Doepfer Musikelektronik GmbH',
      0x21: 'Creative ATC / E-mu',
      0x22: 'Seyddo/Minami',
      0x23: 'LG Electronics (Goldstar)',
      0x24: 'Midisoft sas di M.Cima & C',
      0x25: 'Samick Musical Inst. Co. Ltd.',
      0x26: 'Penny and Giles (Bowthorpe PLC)',
      0x27: 'Acorn Computer',
      0x28: 'LSC Electronics Pty. Ltd.',
      0x29: 'Focusrite/Novation',
      0x2a: 'Samkyung Mechatronics',
      0x2b: 'Medeli Electronics Co.',
      0x2c: 'Charlie Lab SRL',
      0x2d: 'Blue Chip Music Technology',
      0x2e: 'BEE OH Corp',
      0x2f: 'LG Semicon America',
      0x30: 'TESI',
      0x31: 'EMAGIC',
      0x32: 'Behringer GmbH',
      0x33: 'Access Music Electronics',
      0x34: 'Synoptic',
      0x35: 'Hanmesoft',
      0x36: 'Terratec Electronic GmbH',
      0x37: 'Proel SpA',
      0x38: 'IBK MIDI',
      0x39: 'IRCAM',
      0x3a: 'Propellerhead Software',
      0x3b: 'Red Sound Systems Ltd',
      0x3c: 'Elektron ESI AB',
      0x3d: 'Sintefex Audio',
      0x3e: 'MAM (Music and More)',
      0x3f: 'Amsaro GmbH',
      0x40: 'CDS Advanced Technology BV (Lanbox)',
      0x41: 'Mode Machines (Touched By Sound GmbH)',
      0x42: 'DSP Arts',
      0x43: 'Phil Rees Music Tech',
      0x44: 'Stamer Musikanlagen GmbH',
      0x45: 'Musical Muntaner S.A. dba Soundart',
      0x46: 'C-Mexx Software',
      0x47: 'Klavis Technologies',
      0x48: 'Noteheads AB',
      0x49: 'Algorithmix',
      0x4a: 'Skrydstrup R&D',
      0x4b: 'Professional Audio Company',
      0x4c: 'NewWave Labs (MadWaves)',
      0x4d: 'Vermona',
      0x4e: 'Nokia',
      0x4f: 'Wave Idea',
      0x50: 'Hartmann GmbH',
      0x51: "Lion's Tracs",
      0x52: 'Analogue Systems',
      0x53: 'Focal-JMlab',
      0x54: 'Ringway Electronics (Chang-Zhou) Co Ltd',
      0x55: 'Faith Technologies (Digiplug)',
      0x56: 'Showworks',
      0x57: 'Manikin Electronic',
      0x58: '1 Come Tech',
      0x59: 'Phonic Corp',
      0x5a: 'Dolby Australia (Lake)',
      0x5b: 'Silansys Technologies',
      0x5c: 'Winbond Electronics',
      0x5d: 'Cinetix Medien und Interface GmbH',
      0x5e: 'A&G Soluzioni Digitali',
      0x5f: 'Sequentix GmbH',
      0x60: 'Oram Pro Audio',
      0x61: 'Be4 Ltd',
      0x62: 'Infection Music',
      0x63: 'Central Music Co. (CME)',
      0x64: 'genoQs Machines GmbH',
      0x65: 'Medialon',
      0x66: 'Waves Audio Ltd',
      0x67: 'Jerash Labs',
      0x68: 'Da Fact',
      0x69: 'Elby Designs',
      0x6a: 'Spectral Audio',
      0x6b: 'Arturia',
      0x6c: 'Vixid',
      0x6d: 'C-Thru Music',
      0x6e: 'Ya Horng Electronic Co LTD',
      0x6f: 'SM Pro Audio',
      0x70: 'OTO Machines',
      0x71: 'ELZAB S.A. (G LAB)',
      0x72: 'Blackstar Amplification Ltd',
      0x73: 'M3i Technologies GmbH',
      0x74: 'Gemalto (from Xiring)',
      0x75: 'Prostage SL',
      0x76: 'Teenage Engineering',
      0x77: 'Tobias Erichsen Consulting',
      0x78: 'Nixer Ltd',
      0x79: 'Hanpin Electron Co Ltd',
      0x7a: '"MIDI-hardware" R.Sowa',
      0x7b: 'Beyond Music Industrial Ltd',
      0x7c: 'Kiss Box B.V.',
      0x7d: 'Misa Digital Technologies Ltd',
      0x7e: 'AI Musics Technology Inc',
      0x7f: 'Serato Inc LP'
    },
    0x21: {
      0x00: 'Limex',
      0x01: 'Kyodday (Tokai)',
      0x02: 'Mutable Instruments',
      0x03: 'PreSonus Software Ltd',
      0x04: 'Ingenico (was Xiring)',
      0x05: 'Fairlight Instruments Pty Ltd',
      0x06: 'Musicom Lab',
      0x07: 'Modal Electronics (Modulus/VacoLoco)',
      0x08: 'RWA (Hong Kong) Limited',
      0x09: 'Native Instruments',
      0x0a: 'Naonext',
      0x0b: 'MFB',
      0x0c: 'Teknel Research',
      0x0d: 'Ploytec GmbH',
      0x0e: 'Surfin Kangaroo Studio',
      0x0f: 'Philips Electronics HK Ltd',
      0x10: 'ROLI Ltd',
      0x11: 'Panda-Audio Ltd',
      0x12: 'BauM Software',
      0x13: 'Machinewerks Ltd.',
      0x14: 'Xiamen Elane Electronics',
      0x15: 'Marshall Amplification PLC',
      0x16: 'Kiwitechnics Ltd',
      0x17: 'Rob Papen',
      0x18: 'Spicetone OU',
      0x19: 'V3Sound',
      0x1a: 'IK Multimedia',
      0x1b: 'Novalia Ltd',
      0x1c: 'Modor Music',
      0x1d: 'Ableton',
      0x1e: 'Dtronics',
      0x1f: 'ZAQ Audio',
      0x20: 'Muabaobao Education Technology Co Ltd',
      0x21: 'Flux Effects',
      0x22: 'Audiothingies (MCDA)',
      0x23: 'Retrokits',
      0x24: 'Morningstar FX Pte Ltd',
      0x25: 'Changsha Hotone Audio Co Ltd',
      0x26: 'Expressive E',
      0x27: 'Expert Sleepers Ltd',
      0x28: 'Timecode-Vision Technology',
      0x29: 'Hornberg Research GbR',
      0x2a: 'Sonic Potions',
      0x2b: 'Audiofront',
      0x2c: "Fred's Lab",
      0x2d: 'Audio Modeling',
      0x2e: 'C. Bechstein Digital GmbH',
      0x2f: 'Motas Electronics Ltd',
      0x30: 'Elk Audio',
      0x31: 'Sonic Academy Ltd',
      0x32: 'Bome Software',
      0x33: 'AODYO SAS',
      0x34: 'Pianoforce S.R.O',
      0x35: 'Dreadbox P.C.',
      0x36: 'TouchKeys Instruments Ltd',
      0x37: 'The Gigrig Ltd',
      0x38: 'ALM Co',
      0x39: 'CH Sound Design',
      0x3a: 'Beat Bars',
      0x3b: 'Blokas',
      0x3c: 'GEWA Music GmbH',
      0x3d: 'dadamachines',
      0x3e: 'Augmented Instruments Ltd (Bela)',
      0x3f: 'Supercritical Ltd',
      0x40: 'Genki Instruments',
      0x41: 'Marienberg Devices Germany',
      0x42: 'Supperware Ltd',
      0x43: 'Imoxplus BVBA ',
      0x44: 'Swapp Technologies SRL',
      0x45: 'Electra One S.R.O.',
      0x46: 'Digital Clef Limited',
      0x47: 'Paul Whittington Group Ltd',
      0x48: 'Music Hackspace',
      0x49: 'Bitwig GMBH',
      0x4a: 'Enhancia',
      0x4b: 'KV 331',
      0x4c: 'Tehnicadelarte',
      0x4d: 'Endlesss Studio',
      0x4e: 'Dongguan MIDIPLUS Co., LTD',
      0x4f: 'Gracely Pty Ltd.',
      0x50: 'Embodme',
      0x51: 'MuseScore',
      0x52: 'EPFL (E-Lab)',
      0x53: 'Orb3 Ltd.',
      0x54: 'Pitch Innovations',
      0x55: 'Playces ',
      0x56: 'UDO Audio LTD',
      0x57: 'RSS Sound Design',
      0x58: 'Nonlinear Labs GmbH',
      0x59: 'Robkoo Information & Technologies Co., Ltd.',
      0x5a: 'Cari Electronic',
      0x5b: 'Oxi Electronic Instruments SL',
      0x5c: 'XMPT',
      0x5d: 'SHANGHAI HUAXIN MUSICAL INSTRUMENT ',
      0x5e: 'Shenzhen Huashi Technology Co., Ltd',
      0x60: 'Guangzhou Rantion Technology Co., Ltd. ',
      0x61: 'Ryme Music',
      0x62: 'GS Music',
      0x63: 'Shenzhen Flamma Innovation Co., Ltd',
      0x64: 'Shenzhen Mooer Audio Co.,LTD. ',
      0x65: 'Raw Material Software Limited (JUCE)',
      0x66: 'Birdkids',
      0x67: 'Beijing QianYinHuLian Tech. Co',
      0x68: 'Nimikry Music OG',
      0x69: 'Newzik',
      0x6a: 'Hamburg Wave',
      0x6b: 'Grimm Audio',
      0x6c: 'Arcana Instruments LTD.',
      0x6d: 'GameChanger Audio',
      0x6e: 'OakTone',
      0x6f: 'The Digi-Gurdy: A MIDI Hurdy Gurdy',
      0x70: 'MusiKraken',
      0x71: 'PhotoSynth > InterFACE',
      0x72: 'Instruments of Things'
    },
    0x40: {
      0x00: 'Crimson Technology Inc.',
      0x01: 'Softbank Mobile Corp',
      0x03: 'D&M Holdings Inc.',
      0x04: 'Xing Inc.',
      0x05: 'AlphaTheta Corporation',
      0x06: 'Pioneer Corporation',
      0x07: 'Slik Corporation'
    }
  },
  0x01: 'Sequential Circuits',
  0x02: 'IDP',
  0x03: 'Voyetra Turtle Beach, Inc.',
  0x04: 'Moog Music',
  0x05: 'Passport Designs',
  0x06: 'Lexicon Inc.',
  0x07: 'Kurzweil / Young Chang',
  0x08: 'Fender',
  0x09: 'MIDI9',
  0x0a: 'AKG Acoustics',
  0x0b: 'Voyce Music',
  0x0c: 'WaveFrame (Timeline)',
  0x0d: 'ADA Signal Processors, Inc.',
  0x0e: 'Garfield Electronics',
  0x0f: 'Ensoniq',
  0x10: 'Oberheim / Gibson Labs',
  0x11: 'Apple',
  0x12: 'Grey Matter Response',
  0x13: 'Digidesign Inc.',
  0x14: 'Palmtree Instruments',
  0x15: 'JLCooper Electronics',
  0x16: 'Lowrey Organ Company',
  0x17: 'Adams-Smith',
  0x18: 'E-mu',
  0x19: 'Harmony Systems',
  0x1a: 'ART',
  0x1b: 'Baldwin',
  0x1c: 'Eventide',
  0x1d: 'Inventronics',
  0x1e: 'Key Concepts',
  0x1f: 'Clarity',
  0x20: 'Passac',
  0x21: 'Proel Labs (SIEL)',
  0x22: 'Synthaxe (UK)',
  0x23: 'Stepp',
  0x24: 'Hohner',
  0x25: 'Twister',
  0x26: 'Ketron s.r.l.',
  0x27: 'Jellinghaus MS',
  0x28: 'Southworth Music Systems',
  0x29: 'PPG (Germany)',
  0x2a: 'JEN',
  0x2b: 'Solid State Logic Organ Systems',
  0x2c: 'Audio Veritrieb-P. Struven',
  0x2d: 'Neve',
  0x2e: 'Soundtracs Ltd.',
  0x2f: 'Elka',
  0x30: 'Dynacord',
  0x31: 'Viscount International Spa (Intercontinental Electronics)',
  0x32: 'Drawmer',
  0x33: 'Clavia Digital Instruments',
  0x34: 'Audio Architecture',
  0x35: 'Generalmusic Corp SpA',
  0x36: 'Cheetah Marketing',
  0x37: 'C.T.M.',
  0x38: 'Simmons UK',
  0x39: 'Soundcraft Electronics',
  0x3a: 'Steinberg Media Technologies GmbH',
  0x3b: 'Wersi Gmbh',
  0x3c: 'AVAB Niethammer AB',
  0x3d: 'Digigram',
  0x3e: 'Waldorf Electronics GmbH',
  0x3f: 'Quasimidi',
  0x40: 'Kawai Musical Instruments MFG. CO. Ltd',
  0x41: 'Roland Corporation',
  0x42: 'Korg Inc.',
  0x43: 'Yamaha Corporation',
  0x44: 'Casio Computer Co. Ltd',
  0x46: 'Kamiya Studio Co. Ltd',
  0x47: 'Akai Electric Co. Ltd.',
  0x48: 'Victor Company of Japan, Ltd.',
  0x4b: 'Fujitsu Limited',
  0x4c: 'Sony Corporation',
  0x4e: 'Teac Corporation',
  0x50: 'Matsushita Electric Industrial Co. , Ltd',
  0x51: 'Fostex Corporation',
  0x52: 'Zoom Corporation',
  0x54: 'Matsushita Communication Industrial Co., Ltd.',
  0x55: 'Suzuki Musical Instruments MFG. Co., Ltd.',
  0x56: 'Fuji Sound Corporation Ltd.',
  0x57: 'Acoustic Technical Laboratory, Inc.',
  0x59: 'Faith, Inc.',
  0x5a: 'Internet Corporation',
  0x5c: 'Seekers Co. Ltd.',
  0x5f: 'SD Card Association'
  // 0x60-7F [Reserved for Other Uses]
}
